### ISSUE TITLE
Create user database

### ISSUE THREAD

**Issue by schote** [brain-link/scanhub#54]
- Identify suitable database
- Evaluation of [FastAPI Users](https://fastapi-users.github.io/fastapi-users/12.1/) which is a ready-to-use and customizable users management for FastAPI
- Setup user database in a new docker container
- Discussion of database entries
- Evaluation of user roles (admin, user, observer... )

**Comment by BenWilhelmUniklinikFreiburg** [comment]
Did not use FastAPI Users, but implemented the same structure (62f78bfd8430d34a0c0b14c1adca65d1257bc5be).
