### ISSUE TITLE
Allow special characters for database entries

### ISSUE THREAD

**Issue by schote** [brain-link/scanhub#79]
Currently special characters like "@" cannot processed. The following response was captured when creating a new workflow item via the swagger UI.

```
{
  "detail": [
    {
      "loc": [
        "body",
        213
      ],
      "msg": "Invalid control character at: line 7 column 30 (char 213)",
      "type": "value_error.jsondecode",
      "ctx": {
        "msg": "Invalid control character at",
        "doc": "{\n  \"name\": \"reco_2d\",\n  \"description\": \"End-to-end image reconstruction workflow for low-field MRI\",\n  \"version\": \"0.0.1\",\n  \"author\": \"david.schote@brain-link.de\",\n  \"definition\": {\n    \"tasks\": {\"input\": \"data}\n  }\n}",
        "pos": 213,
        "lineno": 7,
        "colno": 30
      }
    }
  ]
}
```

**Comment by schote** [comment]
Also `_`, `-`, `.` are not allowed but required to denote version number for instance

**Comment by BenWilhelmUniklinikFreiburg** [comment]
Just checked and it works now. It works in regular database entries and in entries that contain a json. 

I used this commit to check: https://github.com/brain-link/scanhub/commit/9487164d7885082e562709036123c76e43143aa8

@schote if you don't have objections, I would close this issue.
